apiVersion: apps/v1
kind: Deployment
metadata:
  name: netutil
  labels:
    app: netutil 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netutil 
  template:
    metadata:
      labels:
        app: netutil
    spec:
      containers:
      - name: netutil
        image: srampal/nginx-netutils:2
        ports:
        - containerPort: 80

